import re
import os
import json
import hashlib
import requests
from datetime import datetime
from git import Repo
from collections import defaultdict


class DSTerminalReleaseEngineV2:

    def __init__(self, repo_path=".", github_token=None, repo_name=None):
        self.repo = Repo(repo_path)
        self.github_token = github_token
        self.repo_name = repo_name

    # ---------------------------
    # 1. GET COMMITS
    # ---------------------------
    def get_commits(self, since_tag=None):
        commits = list(self.repo.iter_commits("HEAD"))

        if since_tag:
            commits = list(self.repo.iter_commits(f"{since_tag}..HEAD"))

        return commits

    # ---------------------------
    # 2. CLASSIFY COMMITS
    # ---------------------------
    def classify_commits(self, commits):
        categories = defaultdict(list)

        patterns = {
            "feat": r"feat|feature",
            "fix": r"fix|bug",
            "security": r"security|hardening|auth|vuln",
            "docs": r"doc|readme",
            "refactor": r"refactor|cleanup",
            "perf": r"perf|optimize"
        }

        for c in commits:
            msg = c.message.lower()

            matched = False
            for k, p in patterns.items():
                if re.search(p, msg):
                    categories[k].append(c)
                    matched = True
                    break

            if not matched:
                categories["other"].append(c)

        return categories

    # ---------------------------
    # 3. SEMANTIC VERSIONING
    # ---------------------------
    def bump_version(self, latest_tag, categories):
        major, minor, patch = map(int, latest_tag.replace("v", "").split("."))

        if categories.get("security") or categories.get("feat"):
            minor += 1
            patch = 0
        elif categories.get("fix"):
            patch += 1

        return f"v{major}.{minor}.{patch}"

    # ---------------------------
    # 4. BUILD CHANGELOG
    # ---------------------------
    def build_changelog(self, categorized):
        md = []

        emoji_map = {
            "feat": "✨ Features",
            "fix": "🐛 Fixes",
            "security": "🛡️ Security",
            "docs": "📄 Documentation",
            "refactor": "♻️ Refactor",
            "perf": "⚡ Performance",
            "other": "🔧 Other"
        }

        for key, commits in categorized.items():
            if not commits:
                continue

            md.append(f"## {emoji_map.get(key, key)}")

            for c in commits:
                msg = c.message.split("\n")[0]
                md.append(f"- {msg} (`{c.hexsha[:7]}`)")

            md.append("")

        return "\n".join(md)

    # ---------------------------
    # 5. SHA256 ARTIFACT SIGNING
    # ---------------------------
    def generate_checksum(self, file_path):
        sha256 = hashlib.sha256()

        with open(file_path, "rb") as f:
            while chunk := f.read(8192):
                sha256.update(chunk)

        return sha256.hexdigest()

    # ---------------------------
    # 6. BUILD RELEASE MARKDOWN
    # ---------------------------
    def build_release(self, version, changelog):
        date = datetime.utcnow().strftime("%Y-%m-%d")

        return f"""# 🚀 DSTerminal Release {version}

**Release Date:** {date}

---

## 📋 Changelog

{changelog}

---

## 🧠 System Notes
- Auto-generated by DSTerminal Release Engine v2
- Semantic versioning enabled
- Commit-based classification applied

---

## 🔗 Links
- Repository: https://github.com/{self.repo_name}
"""

    # ---------------------------
    # 7. CREATE GITHUB RELEASE
    # ---------------------------
    def publish_github_release(self, version, body, assets=None):
        if not self.github_token or not self.repo_name:
            print("GitHub publishing disabled (missing token/repo)")
            return

        url = f"https://api.github.com/repos/{self.repo_name}/releases"

        headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github+json"
        }

        data = {
            "tag_name": version,
            "name": f"DSTerminal {version}",
            "body": body,
            "draft": False,
            "prerelease": False
        }

        response = requests.post(url, headers=headers, json=data)

        if response.status_code == 201:
            print("✅ GitHub release published")
        else:
            print("❌ Failed:", response.text)

    # ---------------------------
    # 8. RUN PIPELINE
    # ---------------------------
    def run(self, latest_tag="v0.0.0"):
        commits = self.get_commits(latest_tag)
        categorized = self.classify_commits(commits)

        version = self.bump_version(latest_tag, categorized)
        changelog = self.build_changelog(categorized)

        release_md = self.build_release(version, changelog)

        return version, release_md